apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dalekseev-dedicatted/tf-eks.git
    targetRevision: main
    path: cd/app/
  destination:
    server: https://kubernetes.default.svc
    namespace: cd-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
